---

collections:
  # Install a collection from Ansible Galaxy.
  - name: vmware.vmware_rest
    version: 2.2.0
    source: https://galaxy.ansible.com

  - name: community.vmware
    version: 2.9.1
    source: https://galaxy.ansible.com

  - name: community.general
    version: 5.8.0
    source: https://galaxy.ansible.com

  - name: cisco.ios
    version: 4.0.0
    source: https://galaxy.ansible.com
