---
- name: Compare IOS config with baseline config
  hosts: 172.16.94.4
  gather_facts: no
  
  vars:
    baseline_config: "/baseline/172.16.94.4.txt"
    current_config: "show running-config"
    config_changes: []
  
  tasks:
    - name: Get current IOS config
      ios_command:
        commands: "{{ current_config | b64decode }}"
      register: current_output
    
    - name: Get baseline IOS config
      slurp:
        src: "{{ baseline_config }}"
      register: baseline_output
      delegate_to: backup-server
          
    - name: Run diff between current config and baseline config
      set_fact:
        config_diff: "{{ current_config.stdout[0] | diff(baseline_config.content ) | join('\n') }}"

    - name: Push baseline config if configs differ
      ios_config:
        lines: "{{ lookup('file', baseline_config_file).split('\n') }}"
      when: config_diff != ""
