---
- name: Compare IOS config with baseline config
  hosts: 172.16.94.4
  gather_facts: no
  
  vars:
    baseline_config: "baseline/172.16.94.4.txt"
    current_config: "show running-config"
    config_changes: []
  
  tasks:
    - name: Get current IOS config
      ios_command:
        commands: "{{ current_config }}"
      register: current_output
    
    - name: Get baseline IOS config
      slurp:
        src: "{{ baseline_config }}"
      register: baseline_output
      delegate_to: backup-server
          
    - name: Compare configs
      set_fact:
        config_changes: "{{ current_output.stdout[0] | diff(baseline_output.content | b64decode).diff }}"

    - name: Push baseline config if changes have been made
      ios_config:
        lines: "{{ lookup('file', baseline_config).splitlines() }}"
        replace: yes
      when: config_changes != []
