---
- name: Compare IOS config with baseline config
  hosts: 172.16.94.4
  gather_facts: no
  
  vars:
    baseline_config: "/baseline/172.16.94.4.txt"
    current_config: "show running-config"
    config_changes: []
  
  tasks:
    - name: Get current IOS config
      ios_command:
        commands: "{{ current_config }}"
      register: current_output
    
    - name: Get baseline IOS config
      slurp:
        src: "{{ baseline_config }}"
      register: baseline_output
      delegate_to: backup-server
          
    - name: Compare current config to baseline config
      set_fact:
        configs_match: "{{ current_config.stdout[0] == baseline_config.content | b64decode | join('\n') }}"

    - name: Push baseline config if configs do not match
      ios_config:
        lines: "{{ baseline_config.split('\n') }}"
      when: not configs_match
