---
- name: Pull and compare IOS config with baseline, push baseline if different
  hosts: cisco_ios_devices
  gather_facts: no
  vars:
    baseline_config_file: "/path/to/baseline_config.txt"
  tasks:
    - name: Get current IOS config
      ios_command:
        commands:
          - "show running-config"
      register: current_config

    - name: Read baseline config from file
      slurp:
        src: "{{ baseline_config_file }}"
      register: baseline_config
      delegate_to: backup-server

    - name: Run diff between current config and baseline config
      set_fact:
        config_diff: "{{ current_config.stdout[0] | diff(baseline_config.content | b64decode) | join('\n') }}"

    - name: Push baseline config if configs differ
      ios_config:
        lines: "{{ lookup('file', baseline_config_file).split('\n') }}"
      when: config_diff != ""
