---
- name: Pull and Compare IOS Config
  hosts: 172.16.94.4
  gather_facts: no
  connection: network_cli

  vars:
    baseline_config_file: "baseline_config.txt"

  tasks:
    - name: Retrieve running config from device
      ios_command:
        commands:
          - show running-config | begin version
      register: current_config

    - name: Compare current config to baseline config
      set_fact:
        configs_match: "{{ current_config.stdout_lines[0] == lookup('file', baseline_config_file) }}"

    - name: Configure device with baseline config
      ios_config:
        lines: "{{ lookup('file', baseline_config_file).split('\n') }}"
      when: not configs_match
