---
- name: Pull and compare IOS config with baseline, push baseline if different
  hosts: 172.16.94.4
  gather_facts: no
  vars:
    baseline_file: "/baseline/172.16.94.4.txt"
  tasks:
    - name: Get current IOS config
      ios_command:
        commands:
          - "show running-config"
      register: current_config

    - name: Compare current config with baseline
      command: diff {{ baseline_file }} <(echo "{{ current_config.stdout }}")
      register: diff_output
      changed_when: diff_output.stdout != ""
      delegate_to: backup-server
