- name: compare files 
  hosts: backup-server
  gather_facts: false

  tasks:
  - name: find differences in files between directories
    find:
     paths: /backup/
     file_type: file
     recurse: yes
    register: dir1_files
  - name: find differences in files between directories
    find:
     paths: /postchange/
     file_type: file
     recurse: yes
    register: dir2_files
  - name: save output of diff in a log file
    debug:
     msg: "{{ item.diff }}"
    with_items: "{{ dir1_files.files|diff(dir2_files.files) }}"
