- name: Copy File
  hosts: 172.21.142.155

  tasks:
  - name: Copy file
    ansible.builtin.template:
      remote_src=yes
      src: /home/ansible/test.conf
      dest: /home/ansible/testing/test.conf
