---
- name: Open Firewall Port
  hosts: "{{ hostname }}"

  tasks:
  - name: Permit traffic on provided port
    ansible.posix.firewalld:
    port: "{{ port_protocol }}"
    permanent: yes
    state: enabled
