- name: Update web servers
  hosts: AIOP-VA-NFS-V01
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Copy file
    ansible.builtin.template:
      src: /home/ansible/test.conf
      dest: /home/ansible/testing/test.conf
