---

- name: Increase RAM
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Increase RAM
      community.vmware.vmware_guest:
        hostname: "172.16.64.140"
        validate_certs: False
        name: "{{ vm_name }}"
        hardware:
          hotadd_memory: true
          memory_mb: "{{ mem_mb }}"