---
  - name: capture show output
    hosts: " {{ ip_address }} "
    gather_facts: no
    connection: network_cli

    tasks: 

      - name: show run
        ios_command:
          commands:
          - show run
          - show version
        register: config

      - name: save output to local directory
        hosts: 172.21.142.150
        copy:
          content: "{{ config.stdout | replace('\\n', '\n') }}"
          dest: "/show-output/{{ inventory_hostname }}"
          remote_src: yes
