---
  - name: capture show output
    hosts: " {{ ip_address }} "
    gather_facts: no

    tasks: 

      - name: show run
        ios_command:
          commands:
          - show run
          - show version
        register: config

      - name: save output to local directory
        copy:
        delegate_to: 127.0.0.1
          content: "{{ config.stdout | replace('\\n', '\n') }}"
          dest: "/home/config_output.txt"
          remote_src: yes
