---
  - name: capture show output
    hosts: " {{ ip_address }} "
    gather_facts: no
    connection: network_cli

    tasks: 

      - name: show run
        ios_command:
          commands:
          - show run
          - show version
        register: config

      - name: save output to local directory
        copy:
          content: "{{ config.stdout | replace('\\n', '\n') }}"
          dest: "./show-output/{{ inventory_hostname }}.ios"
