- name: Backup IOS config, upgrade IOS, and verify config
  hosts: cisco_devices
  gather_facts: no

  vars:
    ios_image: "ios file name"
    ios_image_old: "ios file name"
    backup_dir: "/home/user/ios_backups"

  tasks:
    - name: Backup IOS config
      ios_command:
        commands: "show running-config | begin hostname"
      register: current_config

    - name: Save current config to backup file
      copy:
        content: "{{ current_config.stdout }}"
        dest: "{{ backup_dir }}/backup.cfg"

    - name: Copy IOS image to device
      ios_command:
        commands:
          - "copy tftp://xxx.xxx.xxx.xxx/{{ ios_image }} flash:"

    - name: Upgrade IOS
      ios_command:
        commands:
          - "conf t"
          - "boot system flash:/{{ ios_image }}"
          - "end"
          - "write memory"
          - "reload in 5"
      delay: 10
      register: upgrade_output

    - name: Wait for device to reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 300
        state: started

    - name: Wait for device to be reachable
      wait_for_connection:

    - name: Verify config after upgrade
      ios_command:
        commands: "show running-config | begin hostname"
      register: upgraded_config

    - name: Compare config to backup
      fail:
        msg: "Configurations differ - rolling back"
      when: current_config.stdout != upgraded_config.stdout

    - name: Roll back to previous IOS version
      ios_command:
        commands:
          - "conf t"
          - "no boot system"
          - "boot system flash:/{{ ios_image_old }}"
          - "end"
          - "write memory"
          - "reload in 5"
      delay: 10
      when: current_config.stdout != upgraded_config.stdout
