---
- hosts: 172.16.71.1
  tasks:
  - name: No Shut
    cisco.ios.ios_config:
      lines:
        # - noshut
        - no shutdown
        # parents: int gig2/0/2
        parents: interface GigabitEthernet2/0/2
