---
- hosts: 172.16.71.1
  tasks:
  - name: Merge provided configuration with device configuration
    cisco.ios.ios_interfaces:
      config:
      - name: GigabitEthernet2/0/2
        enabled: true
