---
- hosts: 172.16.71.1
  connection: ansible.netcommon.network_cli
  
  tasks:
   - name: No shut port
     ios_config:
       lines:
         - no shut
       parents: interface GigabitEthernet2/0/2
