---
- hosts: 172.16.71.1
- gather_facts: no
  tasks:
  - name: Enable Port
    cisco.ios.ios_config:
      lines:
      # - no shut
    - no shutdown
    # parents: int gig2/0/2
    parents: interface GigabitEthernet2/0/2
