---
- hosts: " {{ ip_address }} "
  tasks:
  - name: Ansible copy files remote to remote
    ansible.builtin.copy:
      src: " {{ src_path }} "
      dest: " {{ dest_path }} "
      backup: yes
      remote_src: yes
