---
- hosts: " {{ ip_address }} "
  tasks:
  - name: Ansible copy files remote to remote
    copy:
      src: /home/ansible/test.conf
      dest: /home/ansible/testing
      backup: yes
      remote_src: yes
