---
- hosts: " {{ ip_address }} "
  tasks:
  - name: Ansible copy files remote to remote
    copy:
      remote_src: yes
      src: " {{ src_path }} "
      dest: " {{ dest_path }} "
      backup: yes
      
