---
- hosts: " {{ ip_address }} "
  tasks:
  - name: Ansible copy files remote to remote
    copy:
      backup: yes
      remote_src: yes
      src: " {{ src_path }} "
      dest: " {{ dest_path }} "
      owner: root
      group: root
      mode: 0644
