- name: Backup Cisco Configs to Separate Server
  hosts: 172.16.67.254
  gather_facts: no

  vars:
    backup_server: backup-server
    backup_dir: "/backups/network_configs"

  tasks:
    - name: Check if backup directory exists
      ansible.netcommon.net_command:
        cmd: "[ -d {{ backup_dir }} ] && echo 'Directory exists'"
        register: dir_check
      delegate_to: "{{ backup_server }}"

    - name: Create backup directory if it doesn't exist
      ansible.netcommon.net_command:
        cmd: "mkdir -p {{ backup_dir }}"
      when: "'Directory exists' not in dir_check.stdout"
      delegate_to: "{{ backup_server }}"

    - name: Backup running config 
      ios_command:
        commands:
          - show running-config
      register: cisco_output

    - name: Save running config to backup server
      ansible.netcommon.net_put:
        src: "{{ cisco_output.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}.txt"
        transport: scp
        persistent: yes
      delegate_to: "{{ backup_server }}"
