---
#
# This playbook gets host info
#
- name: Get host info
  hosts: iic-col-vct-v01.iic.csra.nat
  gather_facts: no
  
  tasks:
  - name: "Get host info"
    community.vmware.vmware_host_facts:
      hostname: "iic-col-vct-v01.iic.csra.nat"
      username: "jpoore-adm"
      password: "PsPLtP20122013$1!"
      validate_certs: False
      esxi_hostname: "{{ esxi_hostname }}"
    delegate_to: localhost
    connection: local
    register: host_facts

  - name: "Print Host info"
    debug:
      msg: "{{ host_facts }}"
