- name: Backup Cisco Configs to Separate Server
  hosts: 172.16.67.254
  gather_facts: no

  vars:
    backup_server: backup-server
    backup_dir: "/backups/network_configs"

  tasks:
  
    - name: Create backup directory if it doesn't exist
      ansible.builtin.file:
        path: /backup/
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true
      
    - name: Creating Time Stamp
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: backup-server
      delegate_facts: true
      run_once: true
      register: timestamp

    - name: Backup running config 
      ios_command:
        commands:
          - show running-config
      register: cisco_output

    - name: Save running config to backup server
      copy:
        src: "{{ cisco_output.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-{{ timestamp }}.txt"
      when: cisco_output is defined
      become: true
      delegate_to: "{{ backup_server }}"
