- name: retrieve network configurations
  hosts: network
  gather_facts: no

  tasks:
    # fail with good error for Automation controller user

    - name: backup configuration
      include_role:
        name: "../roles/backup"
      when: ansible_network_os is defined

    - name: create time stamp for play
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: backup-server
      delegate_facts: true
      run_once: true

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backup/
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true

    - name: save configuration to backup server
      copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{hostvars['backup-server'].datetime}}/"
      when: config_output is defined
      become: true
      delegate_to: backup-server
