- name: VMWare tasks
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_ip: '172.16.64.140'
    vmname: 'AIOP-VA-AAP-CN3'
  tasks:
  - name: Dedicate one core to the VM
    vmware.vmware_rest.vcenter_vm_hardware_cpu:
    vm: '{{ vmname }}'
    count: 8
    register: _result
