- hosts: " {{ ip_address }} "
  tasks:
  - name: Restart Windows Service
    ansible.windows.win_service:
      ansible_connection: ssh
      ansible_shell_type: powershell
      name: "{{ svc_name }}"
      state: restarted
